name: codecov

# workflow triggers
on:
  push:
    branches:
      - '**' # every branch
    tags:
      - '**'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  test-and-build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: install packages
        run: |
          pip install wheel
          pip install -r requirements.txt
      - name: unittest
        run: |
          python -m unittest discover -b
          python -m build
  coverage-upload:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: coverage
        run: |
          pip install wheel
          pip install -r requirements.txt
          coverage run -m unittest discover -b
          bash <(curl -s https://codecov.io/bash)
  deploy:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [formatter, test-and-build]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: deploy
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USER }}
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          pip install wheel
          pip install -r requirements.txt
          python -m build
          python -m twine upload dist/*